"""
One-time data preparation for TinyStories experiment.
Downloads TinyStories dataset and creates symlinks for prepare.py compatibility.

Usage:
    python prepare_tinystories.py

This downloads TinyStories data and creates symlinks that prepare.py can read:
- tinystories_gpt4_train.parquet -> shard_00000.parquet
- tinystories_gpt4_val.parquet -> shard_06542.parquet (the validation shard)
"""

import os
import sys
import time
import pickle

import requests
import pyarrow.parquet as pq
import rustbpe
import tiktoken
import torch

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CACHE_DIR = os.path.join(os.path.expanduser("~"), ".cache", "autoresearch")
DATA_DIR = os.path.join(CACHE_DIR, "data")
TOKENIZER_DIR = os.path.join(CACHE_DIR, "tokenizer")

# TinyStories URLs
BASE_URL = "https://huggingface.co/datasets/karpathy/tinystories-gpt4-clean/resolve/main"
TRAIN_FILENAME = "tinystories_gpt4_train.parquet"
VAL_FILENAME = "tinystories_gpt4_val.parquet"

# Names that prepare.py expects (we'll create symlinks)
TRAIN_SYMLINK = "shard_00000.parquet"
VAL_SYMLINK = "shard_06542.parquet"  # prepare.py expects this as val shard

# Tokenizer config (smaller vocab for simpler text)
VOCAB_SIZE = 4096
SPLIT_PATTERN = r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,2}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+"""
SPECIAL_TOKENS = [f"<|reserved_{i}|>" for i in range(4)]
BOS_TOKEN = "<|reserved_0|>"

# ---------------------------------------------------------------------------
# Download
# ---------------------------------------------------------------------------

def download_file(url, filepath, description="file"):
    """Download a single file with retries."""
    if os.path.exists(filepath):
        file_size_mb = os.path.getsize(filepath) / (1024 * 1024)
        print(f"  ✓ {description} ({file_size_mb:.1f} MB)")
        return True

    max_attempts = 5
    for attempt in range(1, max_attempts + 1):
        try:
            print(f"  Downloading {description} (attempt {attempt}/{max_attempts})...")
            response = requests.get(url, stream=True, timeout=120)
            response.raise_for_status()
            
            total_size = int(response.headers.get('content-length', 0))
            
            temp_path = filepath + ".tmp"
            downloaded = 0
            with open(temp_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)
                        if total_size > 0:
                            pct = (downloaded / total_size) * 100
                            print(f"\r  Downloading {description}: {pct:.1f}%", end="", flush=True)
            
            os.rename(temp_path, filepath)
            print()
            return True
            
        except (requests.RequestException, IOError) as e:
            print(f"\n  Attempt {attempt} failed: {e}")
            for path in [filepath + ".tmp", filepath]:
                if os.path.exists(path):
                    try:
                        os.remove(path)
                    except OSError:
                        pass
            if attempt < max_attempts:
                wait = 2 ** attempt
                print(f"  Waiting {wait}s before retry...")
                time.sleep(wait)
    
    return False


def download_tinystories():
    """Download TinyStories dataset."""
    os.makedirs(DATA_DIR, exist_ok=True)
    
    print("=" * 60)
    print("TinyStories Dataset")
    print("=" * 60)
    print("Children's stories generated by GPT-3.5/4")
    print("Ideal for training small language models")
    print()
    print(f"Cache directory: {DATA_DIR}")
    print()
    
    # Download train file (~1.5GB compressed)
    train_url = f"{BASE_URL}/{TRAIN_FILENAME}"
    train_path = os.path.join(DATA_DIR, TRAIN_FILENAME)
    if not download_file(train_url, train_path, "train file"):
        print("ERROR: Failed to download train file")
        sys.exit(1)
    
    # Download val file (~20MB)
    val_url = f"{BASE_URL}/{VAL_FILENAME}"
    val_path = os.path.join(DATA_DIR, VAL_FILENAME)
    if not download_file(val_url, val_path, "val file"):
        print("ERROR: Failed to download val file")
        sys.exit(1)
    
    # Create symlinks for prepare.py compatibility
    train_symlink_path = os.path.join(DATA_DIR, TRAIN_SYMLINK)
    val_symlink_path = os.path.join(DATA_DIR, VAL_SYMLINK)
    
    # Remove existing symlinks
    for symlink_path in [train_symlink_path, val_symlink_path]:
        if os.path.islink(symlink_path) or os.path.exists(symlink_path):
            os.remove(symlink_path)
    
    # Create symlinks
    os.symlink(train_path, train_symlink_path)
    os.symlink(val_path, val_symlink_path)
    
    print()
    print("Created symlinks for prepare.py compatibility:")
    print(f"  {TRAIN_SYMLINK} -> {TRAIN_FILENAME}")
    print(f"  {VAL_SYMLINK} -> {VAL_FILENAME}")
    print()

# ---------------------------------------------------------------------------
# Tokenizer
# ---------------------------------------------------------------------------

def text_iterator(max_chars=500_000_000, doc_cap=10_000):
    """Yield documents from training file."""
    train_path = os.path.join(DATA_DIR, TRAIN_FILENAME)
    if not os.path.exists(train_path):
        print(f"ERROR: Train file not found: {train_path}")
        sys.exit(1)
    
    nchars = 0
    pf = pq.ParquetFile(train_path)
    for rg_idx in range(pf.num_row_groups):
        rg = pf.read_row_group(rg_idx)
        for text in rg.column("text").to_pylist():
            doc = text[:doc_cap] if len(text) > doc_cap else text
            nchars += len(doc)
            yield doc
            if nchars >= max_chars:
                return


def train_tokenizer():
    """Train BPE tokenizer for TinyStories."""
    tokenizer_pkl = os.path.join(TOKENIZER_DIR, "tokenizer.pkl")
    token_bytes_path = os.path.join(TOKENIZER_DIR, "token_bytes.pt")

    if os.path.exists(tokenizer_pkl) and os.path.exists(token_bytes_path):
        print(f"Tokenizer already exists at {TOKENIZER_DIR}")
        return

    os.makedirs(TOKENIZER_DIR, exist_ok=True)

    print("=" * 60)
    print("Training Tokenizer")
    print("=" * 60)
    print(f"Vocab size: {VOCAB_SIZE}")
    print()
    
    t0 = time.time()

    tokenizer = rustbpe.Tokenizer()
    vocab_size_no_special = VOCAB_SIZE - len(SPECIAL_TOKENS)
    
    print("Training BPE tokenizer...")
    tokenizer.train_from_iterator(text_iterator(), vocab_size_no_special, pattern=SPLIT_PATTERN)

    # Build tiktoken encoding
    pattern = tokenizer.get_pattern()
    mergeable_ranks = {bytes(k): v for k, v in tokenizer.get_mergeable_ranks()}
    tokens_offset = len(mergeable_ranks)
    special_tokens = {name: tokens_offset + i for i, name in enumerate(SPECIAL_TOKENS)}
    enc = tiktoken.Encoding(
        name="rustbpe",
        pat_str=pattern,
        mergeable_ranks=mergeable_ranks,
        special_tokens=special_tokens,
    )

    # Save tokenizer
    with open(tokenizer_pkl, "wb") as f:
        pickle.dump(enc, f)

    t1 = time.time()
    print(f"Trained in {t1 - t0:.1f}s")

    # Build token_bytes lookup
    print("Building token_bytes lookup...")
    special_set = set(SPECIAL_TOKENS)
    token_bytes_list = []
    for token_id in range(enc.n_vocab):
        token_str = enc.decode([token_id])
        if token_str in special_set:
            token_bytes_list.append(0)
        else:
            token_bytes_list.append(len(token_str.encode("utf-8")))
    token_bytes_tensor = torch.tensor(token_bytes_list, dtype=torch.int32)
    torch.save(token_bytes_tensor, token_bytes_path)

    # Sanity check
    test = "Hello world! Numbers: 123. Once upon a time."
    encoded = enc.encode_ordinary(test)
    decoded = enc.decode(encoded)
    assert decoded == test, f"Tokenizer roundtrip failed"
    
    print(f"Tokenizer saved to {TOKENIZER_DIR}")
    print(f"Final vocab size: {enc.n_vocab}")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print()
    print("=" * 60)
    print("TinyStories Data Preparation")
    print("=" * 60)
    print()
    
    # Step 1: Download data
    download_tinystories()
    
    # Step 2: Train tokenizer
    train_tokenizer()
    
    print()
    print("=" * 60)
    print("Done! Ready to train.")
    print("=" * 60)
    print()
    print("Next step: Run training")
    print("  uv run train.py")
    print()
